apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-recommendation-config
data:
  MODELS_DIR: "/app/models/recommendation"
  FLASK_ENV: "production"
  PORT: "5000"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voyage
  template:
    metadata:
      labels:
        app: voyage
    spec:
      containers:
      - name: voyage-app
        image: archanadevrena/voyage-analytics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: hotel-recommendation-config

---
apiVersion: v1
kind: Service
metadata:
  name: voyage-app
spec:
  type: LoadBalancer #NodePort
  selector:
    app: voyage
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
